apiVersion: crisarias.com/v1alpha1
kind: MpiCluster
metadata:
  labels:
    app.kubernetes.io/name: poascluster
    app.kubernetes.io/instance: poascluster-instance
    app.kubernetes.io/part-of: kubernetes-mpi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-mpi-operator
  name: poascluster
spec:
  clusterName: "poas"
  clusterNodeImage: "docker.io/crisarias/mpicluster-mpich-slurm-operator-base:latest"
  clusterNodesCount: 3
  coresPerNode: 3
  memoryPerNode: 2000
  useHostNetwork: false
  sshPort: 22
  sshExternalPort: 22
  localVolumePath: "/mnt/beegfs"
  localVolumeCapacity: 500
