apiVersion: crisarias.com/v1alpha1
kind: MpiCluster
metadata:
  labels:
    app.kubernetes.io/name: barvacluster
    app.kubernetes.io/instance: barvacluster-instance
    app.kubernetes.io/part-of: kubernetes-mpi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-mpi-operator
  name: barvacluster
spec:
  clusterName: "barva"
  clusterNodeImage: "docker.io/crisarias/mpicluster-openmpi-operator-base:latest"
  clusterNodesCount: 8
  coresPerNode: 15
  memoryPerNode: 30000
  sshPort: 22
  localVolumePath: "/mnt/beegfs"
  localVolumeCapacity: 500
