apiVersion: crisarias.com/v1alpha1
kind: MpiJob
metadata:
  labels:
    app.kubernetes.io/name: mpijob
    app.kubernetes.io/instance: mpijob-instance
    app.kubernetes.io/part-of: kubernetes-mpi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-mpi-operator
  name: mpijob
spec:
  jobName: "openmpiJob"
  clusterName: "barva"
  command: git clone https://github.com/Crisarias/mpich-examples && cd mpi-examples/mpi-hello-world/code && make && mpirun -hostfile /nfs/hosts.openmpi -n 120 ./mpi_hello_world > result.txt