apiVersion: crisarias.com/v1alpha1
kind: MpiJob
metadata:
  labels:
    app.kubernetes.io/name: mpijob
    app.kubernetes.io/instance: mpijob-instance
    app.kubernetes.io/part-of: kubernetes-mpi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-mpi-operator
  name: mpichjob
spec:
  jobName: "mpichjob"
  clusterName: "irazu"
  command: source ~/.bashrc && git clone https://github.com/Crisarias/mpich-examples && cd mpich-examples/mpi-hello-world/code && make && mpirun -np 120 ./mpi_hello_world >> /nfs/result.txt