apiVersion: crisarias.com/v1alpha1
kind: MpiCluster
metadata:
  labels:
    app.kubernetes.io/name: barvacluster
    app.kubernetes.io/instance: barvacluster-instance
    app.kubernetes.io/part-of: kubernetes-mpi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-mpi-operator
  name: barvacluster
spec:
  clusterName: "barva"
  clusterNodeImage: "docker.io/crisarias/mpicluster-openmpi-conda-operator-base:latest"
  clusterNodesCount: 2
  coresPerNode: 5
  memoryPerNode: 58000
  sharedMemoryPerNode: 2000
  sshPort: 22
  localVolumePath: "/mnt/beegfs"
  localVolumeCapacity: 500
  enableNvidiaGPU: true
  numGPUs: 1
  nameGPUs: GRID-A100D-3-40C-MIG-3g.40gb


