apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-mpi-operator-v0-0-1-sub
  namespace: operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: kubernetes-mpi-operator
  source: kubernetes-mpi-operator-catalog
  sourceNamespace: operators